Vagrant.configure(2)  do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "graylog"

  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'
  config.vm.network :forwarded_port, guest: 5044, host: 5044, protocol: 'tcp'
  config.vm.network :forwarded_port, guest: 5044, host: 5044, protocol: 'udp'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  $script = <<SCRIPT
    apt-get update
    echo 'Going to download Graylog...'
    curl -S -s -L -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
    dpkg -i graylog_latest.deb
    rm graylog_latest.deb
    curl -S -s -L https://github.com/magicdude4eva/graylog-jira-alarmcallback/releases/download/1.0.8/graylog-plugin-jira-1.0.8.jar -o /opt/graylog/plugin/graylog-plugin-jira-1.0.8.jar
    graylog-ctl set-external-ip http://127.0.0.1:8081/api
    graylog-ctl reconfigure
    graylog-ctl restart
    # Logstash, if needed
    wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://packages.elastic.co/logstash/2.4/debian stable main" | tee -a /etc/apt/sources.list
    apt-get update && apt-get -y install default-jre-headless logstash
    # Setup a user for EurOpen conference: europen/europen
    useradd europen --password '9asFfaNacrcyw' -m -G sudo -s /bin/bash
SCRIPT

  config.vm.provision "shell", inline: $script
end

