---
- name: Enable Logstash repository
  template: src=logstash_repo.j2 
            dest={{ logstash_yum_repo_dest }}
  tags: logstash_repo

- name: Add Logstash Repo Key
  rpm_key: key="{{ logstash_repo_key }}" 
           state=present
  tags: logstash_repo

- name: Install Logstash
  yum: name=logstash
       state=latest
  tags: logstash_install

- name: Configure default settings for Logstash
  template: src=defaults.conf.j2
            dest={{ defaults_RedHat }}
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart logstash
  tags:
   - logstash_defaults
